Added logo into Sidebar component.
UTDNebula/jupiter pull request #151
Opened 2023-10-03 20:22 UTC by KennethImphean

Added logo to Jupiter header in the sidebar component. Together, the logo and the header are centered, but the header itself is off-center. I just followed the format given by the examples from the other projects, but I can change it if need be.

2023-10-03 23:57 UTC, RubenOlano requested changes

2023-10-03 23:57 UTC, RubenOlano commented on src/components/Sidebar.tsx
> +              src="/android-chrome-192x192.png"
Use the `nebula-logo.png` image rather than that old logo

2023-10-04 03:40 UTC, RubenOlano approved these changes
Fixes #131, looks good 👍🏽

2023-10-04 13:26 UTC, Master7130 approved these changes

2023-10-04 14:35 UTC, RubenOlano approved these changes

2023-10-04 14:36 UTC, merged