JUP-4 User Information
UTDNebula/jupiter pull request #157
Opened 2023-10-06 03:43 UTC by danielsuhcompsci

I added a user_metadata table and a junction table for the many-many relationship between user_metadata and clubs (using Drizzle Kit) and a simple settings page for a user to change their information. Added 2 tRPC routes, get and update by ID, although I haven't tested out adding clubs yet, nor is there a UI for it on the settings page (just maps over session.user.clubs and puts a div).

2023-10-06 03:58 UTC, danielsuhcompsci commented
Also, I didn't implement form validation or dropdowns for enums

2023-10-07 22:02 UTC, RubenOlano requested changes
Looks good overall, supabase had `minor` as not nullable so I changed that manually. Remove the console.logs and then I'll approve

2023-10-09 22:15 UTC, RubenOlano approved these changes
👍🏽

2023-10-09 22:20 UTC, Master7130 approved these changes

2023-10-09 22:23 UTC, merged