Jup-13 Join Org Functionality
UTDNebula/jupiter pull request #189
Opened 2023-11-23 19:06 UTC by KennethImphean

Created a Join Button component for users to join clubs along with API procedures to update User_Meta_Data_To_Clubs table in database when users join. The Org Headers and Org Directory components were updated to incorporate the button. When users join a club, the club will then be removed from the Org Directory so that new orgs can be discovered by users.

2023-11-24 03:15 UTC, RubenOlano requested changes
Great looking PR, some changes for the styling stuff but also you can combine the two procedures to make it a little more clean

2023-11-24 03:15 UTC, RubenOlano commented on src/components/JoinButton.tsx
> +            disabled={true}
Can just rewrite this as `disabled`

2023-11-24 03:15 UTC, RubenOlano commented on src/components/JoinButton.tsx
> +            "mr-2 rounded-2xl px-4 py-2 text-xs font-extrabold text-white border-solid disabled:bg-slate-700"
You can rewrite this as 
```
className={`text-xs font-extrabold text-white disabled:bg-slate-700 ${isHeader ? "rounded-full px-8 py-4" : "mr-2 rounded-2xl px-4 py-2 border-solid"
```
I would also add a mouse disabled state, something like `cursor-not-allowed`

2023-11-24 03:15 UTC, RubenOlano commented on src/components/JoinButton.tsx
> +        "bg-blue-primary disabled:bg-blue-700 mr-2 rounded-2xl px-4 py-2 text-xs font-extrabold text-white transition-colors hover:bg-blue-700 "}
Try to combine this one like the comment I left above

2023-11-24 03:15 UTC, RubenOlano commented on src/components/OrgDirectoryGrid.tsx
> +  }
Try moving this logic into the server. COmbine the `all` and `allButJoined` into one query

2023-11-26 03:56 UTC, KennethImphean commented
The changes to styling and combining of the two procedures has been made!

2023-11-26 05:48 UTC, RubenOlano approved these changes
👍🏽

2023-11-26 05:49 UTC, merged