Responsive Changes
UTDNebula/jupiter pull request #196
Opened 2024-01-04 02:24 UTC by nl32

This pr adds tweaks to the layout and styling at different breakpoints to make it more usable on smaller screens and phones. 
this makes most of the core features more usable on mobile, however a lot of it doesn't look perfect 🫣, so comments are greatly appreciated.
One large issue is that the directory grid height shifts whenever new orgs load in.

2024-01-04 03:38 UTC, RubenOlano requested changes
Looks good but some text looks a little to large on smaller screens

2024-02-12 23:14 UTC, nl32 commented on src/app/auth/page.tsx
> +            <h1 className="text-center text-6xl font-bold text-white sm:text-left">
I made the text bigger on the buttons, since it helps readability and fills in the gaps. let me know what you think.

2024-02-12 23:15 UTC, nl32 commented
> Looks good but some text looks a little to large on smaller screens
I made a lot of text everywhere bigger, let me know if you see any other pain points.

2024-02-12 23:18 UTC, RubenOlano commented on src/app/auth/page.tsx
> +            <h1 className="text-center text-6xl font-bold text-white sm:text-left">
Looks good, only thing that sticks out to me is that the button text is not centered but hopefully shouldn't be a crazy fix

2024-02-14 23:54 UTC, Jake3231 commented
@RubenOlano @nl32 What is the expected usability for this PR? "Usable" vs "Polished"? Overall looks great, but there's a fee places that need work but are certainly usable right now.

2024-02-15 00:12 UTC, nl32 commented
> What is the expected usability for this PR? "Usable" vs "Polished"? Overall looks great, but there's a fee places that need work but are certainly usable right now.

The goal was largely to get rid overflow issues on smaller screens, improve readability on smaller screen sizes, and that core features like the directory, events, settings, and all their functionality can be used on mobile, Which I think this pr addresses.
The main areas that I see as having issues are the carrousel, club page header, and events page, which each are being addressed in their own tickets.

@Jake3231 if you see anything else you think needs adjustment or polishing I'd love to hear it.

2024-02-15 00:28 UTC, RubenOlano commented
Only thing I got is the login button stuff not being centered, other than that I'm happy

2024-02-15 00:59 UTC, Jake3231 commented
> > What is the expected usability for this PR? "Usable" vs "Polished"? Overall looks great, but there's a fee places that need work but are certainly usable right now.
> 
> The goal was largely to get rid overflow issues on smaller screens, improve readability on smaller screen sizes, and that core features like the directory, events, settings, and all their functionality can be used on mobile, Which I think this pr addresses. The main areas that I see as having issues are the carrousel, club page header, and events page, which each are being addressed in their own tickets.
> 
> @Jake3231 if you see anything else you think needs adjustment or polishing I'd love to hear it.

The biggest thing is the club page on mobile. If that's a known issue that's being addressed elsewhere, it looks good to me!

2024-02-16 23:18 UTC, RubenOlano approved these changes

2024-02-16 23:19 UTC, merged