Add/feedback page
UTDNebula/jupiter pull request #214
Opened 2024-03-22 05:33 UTC by MistahSanta

Add basic feedback page that send the form data to supabase database and added  a popup after form is submitted.

2024-03-22 06:39 UTC, MistahSanta commented
issue with merging 😭

2024-03-22 06:43 UTC, nl32 commented
did you rebase? commit history seems a bit off

2024-03-23 02:10 UTC, RubenOlano requested changes
Looks pretty good, just one line to delete. I would also add a disabled state on the form whenever a user has already submitted the form. Just so that you can't accidentally spam the form

2024-03-23 02:10 UTC, RubenOlano commented on src/app/feedback/page.tsx
> +//import { useState } from 'react';
Delete this commented line

2024-03-23 02:10 UTC, nl32 requested changes
Feedback form looks clean, though the nebula logo might be a bit redundant, at least not on mobile. no merge issues 😅!

2024-03-23 02:10 UTC, nl32 commented on src/server/db/schema/forms.ts
> +export const forms = pgTable("formSubmission", {
formSubmission might be a bit too vague should probably say it's for the feedback form, also make sure to generate a db migration with `drizzle:generate`.

2024-03-23 03:21 UTC, RubenOlano approved these changes
LGTM

2024-03-23 03:52 UTC, nl32 approved these changes
LGTM

2024-03-23 03:53 UTC, merged