JUP-49 improve club contacts
UTDNebula/jupiter pull request #217
Opened 2024-04-01 22:09 UTC by nl32

this pr adds:
- valid email support.
- url specific validation for all options.

2024-04-02 02:52 UTC, RubenOlano approved these changes
Looks good 👍🏽

2024-04-02 13:28 UTC, RubenOlano requested changes
Discord and email validation seems to work fine

2024-04-02 13:28 UTC, RubenOlano commented on src/utils/contact.ts
Recheck some of the regex for this. Our instagram link is considered invalid, I think you might be missing the www part

2024-04-20 05:18 UTC, danielsuhcompsci approved these changes
I think everything checks out 👌

2024-10-22 20:14 UTC, nl32 commented on src/utils/contact.ts
just decided to remove regex validation, also going to be a nightmare.

2024-10-22 20:15 UTC, merged